project:
  output-dir: docs
  type: website
title: "CSU ESS330 Daily Exercises 27 & 28"
author: "Olivia Gilpin"
date: "05-12-2025"
format:
  html:
    output-file: index.html
    self-contained: true
    toc: true
    toc-depth: 3
    toc-location: left 